Allow Google Drive module to upload to a specified folder
bryancross/key2pdf pull request #17
Opened 2017-01-24 21:56 UTC by tcbyrd

Closes #14 

This adds the `parents` key to the resource object to allow the uploaded PDF to be stored in a folder that is automatically shared with everyone.

2017-01-26 15:53 UTC, azizshamim requested changes

2017-01-26 15:53 UTC, azizshamim commented on gdrive/src/uploadPdf.js
> +      parents: ['0Bx7UhUK81Pz1SE9YZ1JUR0FPbmc']
Is this the specific ID of the folder? Can this be configurable?

2017-01-26 16:01 UTC, tcbyrd commented on gdrive/src/uploadPdf.js
> +      parents: ['0Bx7UhUK81Pz1SE9YZ1JUR0FPbmc']
Yeh, this is a specific folder in our Google Apps account. Could definitely be added to the [`google-config.json`](https://github.com/bryancross/key2pdf/blob/refactoring-to-modules/config/google-config-example.json).

2017-01-26 16:22 UTC, tcbyrd commented
I'm noticing the example configs were put in the root folder. The way the Google Drive module is currently written, it gets its config from a subfolder (`key2pdf/gdrive/config` vs `key2pdf/config`). Not sure what the best practice is here. There are only 2 variables in `google-config.json`, so they could easily be added to `job-template.json`. Thoughts?

2017-02-01 11:48 UTC, bryancross approved these changes
We'll merge the config stuff in a later PR :)  These changes make this more than an MVP.  It's AWESOME!

2017-02-01 11:49 UTC, bryancross commented
@tcbyrd I was looking at that as well when I reviewed your original code.  I think it's fine to merge this PR, and we can tidy up the config stuff later.  

BTW, this is 💯 work!  Super :cool:

2017-02-01 11:49 UTC, merged